# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('city', models.CharField(default='', max_length=50, verbose_name='city')),
                ('state', models.CharField(default='', max_length=2, verbose_name='state')),
                ('country', models.CharField(default='US', max_length=50, verbose_name='country')),
                ('lat', models.FloatField(default='', verbose_name='latitude')),
                ('lon', models.FloatField(default='', verbose_name='longitude')),
            ],
        ),
    ]
